### ISSUE TITLE
Add .env-example width full examples

### ISSUE THREAD

**Issue by gabrin** [GladysAssistant/gladys-gateway#116]
Hello. Can you change .env-example file width full examples in [gladys-gateway-server](https://github.com/GladysAssistant/gladys-gateway/tree/master/src/gladys-gateway-server) ( AWS, STRIPE, URL's, REDIS and ...). Thank you.

**Comment by Pierre-Gilles** [comment]
Hey! Why do you need this? :) 

This repo is public mostly because I want that the code could be readable by the community, but it's not really useful to start the Gladys Gateway yourself ^^

**Comment by gabrin** [comment]
> Hey! Why do you need this? :)
> 
> This repo is public mostly because I want that the code could be readable by the community, but it's not really useful to start the Gladys Gateway yourself ^^

Ok, thank you for answer.  The idea was for the family to make a common gateway and install gladys instead of home assistant

**Comment by Pierre-Gilles** [comment]
Ok, can we talk about this on the forum? :) 

- If you are french, we have a french forum => https://community.gladysassistant.com/
- For international in english => https://en-community.gladysassistant.com/
