### ISSUE TITLE
« 413 Request Entity Too Large » on POST /backups 

### ISSUE THREAD

**Issue by Hamtar0** [GladysAssistant/gladys-gateway#55]
![Screenshot_2020-02-04 Gladys Assistant](https://user-images.githubusercontent.com/1239484/73777424-ae627080-4789-11ea-8bc0-6f59d8530793.png)

**Comment by Hamtar0** [comment]
Available for logs ;)

**Comment by VonOx** [comment]
I confirm issue, trigger a backup does nothing

**Comment by Pierre-Gilles** [comment]
Fixed!
