### ISSUE TITLE
Modules dashboard in the gateway

### ISSUE THREAD

**Issue by tiboys** [GladysAssistant/gladys-gateway#7]
would it be possible to display modules of the dashboard gladys in the gateway? camera, connected users, my wish is to manage everything remotely with the gateway

**Comment by Pierre-Gilles** [comment]
This will be possible with Gladys 4! 

With Gladys 4, the whole Gladys dashboard will be available through the Gateway, even cameras images :) 

Work in progress there => https://github.com/GladysAssistant/gladys-4-playground
