### ISSUE TITLE
Add a way to setup 2FA with key and not QR code for mobile setup

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/gladys-gateway#92]

**Comment by LM1LC3N7** [comment]
On my side, the QRCode is not accepted by Authy. I had to flash it using a standard QRCode scanner and to copy the 2FA seed.

**Comment by Pierre-Gilles** [comment]
Is it really "The QR Code is not accepted by Authy", or you don't have a camera on your device?

I agree it could be nice to display the code and not just a QR code, but flashing with Authy works fine on my side (But with camera indeed)

**Comment by Pierre-Gilles** [comment]
Done
